export const clouds_bg = require('./bg-img/clouds.png')
export const bg_img = require('./bg-img/background_image.png')
export const arrow_back = require('./arrow_back.png')
export const rocket_ios = require('./rocket_ios.png')
export const rocket_android = require('./rocket_android.png')
